/**
 * Client for the events feed.
 *
 * The feed is a static JSON object at a same-origin path, written by a
 * scheduled Lambda in production and by a committed fixture in development.
 * Both live at the same path, so nothing here changes when the Lambda ships.
 *
 * Everything is normalised to one `AppEvent` shape regardless of source
 * platform, so components never branch on where an event came from.
 */

export const EVENTS_ENDPOINT = 'api/events.json';

export type EventSource = 'discord' | 'meetup' | 'twitch' | 'youtube' | 'other';

export interface AppEvent {
  id: string;
  title: string;
  /** ISO 8601 with offset. */
  start: string;
  /** ISO 8601 with offset. Absent for open-ended or unknown-length events. */
  end?: string;
  description?: string;
  /** Human-readable place, or a platform name for online events. */
  location?: string;
  online: boolean;
  url?: string;
  source: EventSource;
}

export interface DiscordSummary {
  online?: number;
  total?: number;
}

export interface EventsPayload {
  /** ISO 8601 timestamp of when the payload was produced. */
  generatedAt: string;
  events: AppEvent[];
  discord?: DiscordSummary;
}

export type EventsResult =
  | { status: 'ok'; payload: EventsPayload }
  | { status: 'error'; error: string };

const SOURCES: readonly EventSource[] = [
  'discord',
  'meetup',
  'twitch',
  'youtube',
  'other',
];

function isEventSource(value: unknown): value is EventSource {
  return typeof value === 'string' && SOURCES.includes(value as EventSource);
}

/**
 * The feed is generated by a separate deployable, so treat it as untrusted:
 * drop malformed entries rather than letting them throw during render.
 */
function normaliseEvent(raw: unknown): AppEvent | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const value = raw as Record<string, unknown>;

  const id = typeof value.id === 'string' ? value.id : null;
  const title = typeof value.title === 'string' ? value.title : null;
  const start = typeof value.start === 'string' ? value.start : null;
  if (!id || !title || !start) return null;
  if (Number.isNaN(Date.parse(start))) return null;

  const end =
    typeof value.end === 'string' && !Number.isNaN(Date.parse(value.end))
      ? value.end
      : undefined;

  return {
    id,
    title,
    start,
    end,
    description:
      typeof value.description === 'string' ? value.description : undefined,
    location: typeof value.location === 'string' ? value.location : undefined,
    online: value.online === true,
    url: typeof value.url === 'string' ? value.url : undefined,
    source: isEventSource(value.source) ? value.source : 'other',
  };
}

function normalisePayload(raw: unknown): EventsPayload {
  const value = (typeof raw === 'object' && raw !== null ? raw : {}) as Record<
    string,
    unknown
  >;

  const events = Array.isArray(value.events)
    ? value.events
        .map(normaliseEvent)
        .filter((event): event is AppEvent => event !== null)
        .sort((a, b) => Date.parse(a.start) - Date.parse(b.start))
    : [];

  const discordRaw = value.discord;
  const discord =
    typeof discordRaw === 'object' && discordRaw !== null
      ? (discordRaw as DiscordSummary)
      : undefined;

  return {
    generatedAt:
      typeof value.generatedAt === 'string'
        ? value.generatedAt
        : new Date(0).toISOString(),
    events,
    discord,
  };
}

/**
 * Resolves the feed URL relative to the deployed base path, so it works at a
 * domain root and under a demo subpath without any code change.
 */
export function eventsUrl(basePath: string): string {
  const prefix = basePath.endsWith('/') ? basePath : `${basePath}/`;
  return `${prefix}${EVENTS_ENDPOINT}`;
}

export async function fetchEvents(url: string): Promise<EventsResult> {
  try {
    const response = await fetch(url, { headers: { accept: 'application/json' } });
    if (!response.ok) {
      return { status: 'error', error: `Feed returned ${response.status}` };
    }
    return { status: 'ok', payload: normalisePayload(await response.json()) };
  } catch (error) {
    return {
      status: 'error',
      error: error instanceof Error ? error.message : 'Network error',
    };
  }
}

/** Events that have not finished yet, soonest first. */
export function upcoming(events: AppEvent[], now = Date.now()): AppEvent[] {
  return events.filter((event) => {
    const finishes = event.end ? Date.parse(event.end) : Date.parse(event.start);
    return finishes >= now;
  });
}
